#!/usr/bin/env python3
"""Extract 仁's left and right components from a cached OFL font.

Usage:
  ~/.cache/oneness-work/venv/bin/python tools/extract-glyph.py \
    ~/.cache/oneness-work/LXGWWenKaiTC-Regular-v1.522.ttf

Dependencies (install outside this repository): fonttools, brotli.
The default output is js/glyph.js; use --output PATH to inspect another font.
"""

import argparse
import hashlib
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.recordingPen import DecomposingRecordingPen, RecordingPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont


def extract(font_path, output):
    font = TTFont(font_path)
    glyphs = font.getGlyphSet()
    glyph_name = font.getBestCmap().get(ord("仁"))
    if glyph_name is None:
        raise ValueError("The font has no U+4EC1 仁 glyph.")

    # Decompose components first so every contour has its own measurable bounds.
    recording = DecomposingRecordingPen(glyphs)
    glyphs[glyph_name].draw(recording)
    contours, current = [], []
    for operation, arguments in recording.value:
        current.append((operation, arguments))
        if operation in ("closePath", "endPath"):
            contour = RecordingPen()
            contour.value = current
            bounds = BoundsPen(glyphs)
            contour.replay(bounds)
            if bounds.bounds:
                contours.append((contour, bounds.bounds))
            current = []
    if current or len(contours) < 2:
        raise ValueError("Expected at least two complete contours for 仁.")

    # 亻 occupies the leftmost cluster. Find the largest gap between contour
    # x-centres, rather than hard-coding contour order or a font-specific index.
    contours.sort(key=lambda item: (item[1][0] + item[1][2]) / 2)
    centres = [(bounds[0] + bounds[2]) / 2 for _, bounds in contours]
    split = max(range(1, len(centres)), key=lambda i: centres[i] - centres[i - 1])
    person, two = contours[:split], contours[split:]
    xmin = min(bounds[0] for _, bounds in contours)
    ymin = min(bounds[1] for _, bounds in contours)
    xmax = max(bounds[2] for _, bounds in contours)
    ymax = max(bounds[3] for _, bounds in contours)
    scale = 920 / max(xmax - xmin, ymax - ymin)
    dx = (1000 - (xmax - xmin) * scale) / 2 - xmin * scale
    dy = (1000 - (ymax - ymin) * scale) / 2 + ymax * scale
    transform = (scale, 0, 0, -scale, dx, dy)

    def svg_path(parts):
        pen = SVGPathPen(glyphs, ntos=lambda value: f"{value:.3f}".rstrip("0").rstrip("."))
        transformed = TransformPen(pen, transform)
        for contour, _ in parts:
            contour.replay(transformed)
        return pen.getCommands()

    digest = hashlib.sha256(Path(font_path).read_bytes()).hexdigest()
    version = font["name"].getDebugName(5) or "unknown version"
    result = (
        "// Derived from LXGW WenKai TC Regular, SIL Open Font License 1.1.\n"
        "// Copyright 2022–2026 LXGW; Copyright 2020 The Klee Project Authors.\n"
        "// https://github.com/lxgw/LxgwWenkaiTC/releases/tag/v1.522\n"
        f"// Font: {version}; SHA-256: {digest}\n"
        "// Generated by tools/extract-glyph.py; see fonts/LICENSES.md.\n"
        f"export const REN_PERSON = '{svg_path(person)}';\n"
        f"export const REN_TWO = '{svg_path(two)}';\n"
        "export const REN_VIEWBOX = '0 0 1000 1000';\n"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(result, encoding="utf-8")
    font.close()
    print(f"Extracted U+4EC1: {len(person)} person contour(s), {len(two)} two contour(s).")
    print(f"Normalized, y-flipped viewBox: 0 0 1000 1000; wrote {output}.")
    print(f"Font SHA-256: {digest}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("font", type=Path, help="Cached LXGW WenKai TC Regular TTF")
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] / "js/glyph.js")
    arguments = parser.parse_args()
    extract(arguments.font.expanduser(), arguments.output)
